### PR TITLE
Add vmap_foreach_tuple_reduce

### PR DESCRIPTION
**Pull request by hthetran**
Builds up on pull request https://github.com/tlx/tlx/pull/7.

Similar to `vmap_foreach_tuple` the `vmap_foreach_tuple_reduce` works on tuples. Additionally to a `Functor` a binary operation `Combine` is required that reduces the mapped components.

Soon the STXXL will have `stxxl::stream::make_tuplestream` and `stxxl::stream::transform` where
e.g. `stxxl::stream::transform` is of type `template <typename Functor, typename... Inputs>`.
The refs to the inputstreams are stored in a `std::tuple<>`. Since both still provide a streaming interface a generic `empty()` method is needed, e.g. it needs to now work on a `std::tuple<Inputs&...>`. With `vmap_foreach_tuple_reduce` one can write the `empty()` method like this:

`bool empty()`
`{return tlx::vmap_foreach_tuple_reduce([](auto & t){ return t.empty(); }, [](bool a, bool b) { return a || b; }, in}`

If this is too specific, we can still just `tlx::vmap_foreach_tuple` and work on the output `std_tuple<bool...>` but maybe it finds use in tlx.

### CODE REVIEW

**Comment by bingmann** [comment]
Hmm. Is this not a combination of two operation: vmap_foreach_tuple. and another vreduce_tuple() ?

**Comment by hthetran** [comment]
I wrote some code for `vreduce` and `vreduce_tuple`. `vmap_foreach_tuple` can be further shortened by `vmap_foreach`.

**Comment by bingmann** [comment]
Getting better. Can you rename the Combine typenames to Reduce, to make the func name.
And currently reduces does (a * (b * (c * d))). I was expecting  (((a * b) * c) * d).
Maybe we need both?

**Comment by hthetran** [comment]
What you suggested sounds like foldl and foldr. I removed `vreduce` and added `foldl`, `foldl_tuple`, `foldr`, `foldr_tuple`. Usually foldl and foldr are used with an initial value, this is included by the typename `Init`. The `empty()` method in `stxxl::make_tuplestream` and `stxxl::transform` would now look like this
`tlx::foldl([](bool a, bool b){return a || b;}, false, tlx::vmap_foreach_tuple([](auto & t){return t.empty();})`.

I think having both options of `foldl` and `foldr` can only be benificial.

**Comment by bingmann** [comment]
Looks good. Will rename foldl() to fold_left(), less internet chat dyslexia. foldr() same.
And add vmap_foreach_tuple_with_index()

**Comment by manpen** [comment]
@bingmann You should write more haskell. This is a commonly accept and much loved name ;)

**Comment by bingmann** [comment]
Hmm, indeed. But nobody likes haskellers :P.

**Comment by bingmann** [comment]
foldl almost sounds like hodl :P

**Comment by bingmann** [comment]
Merged with 8c13153bf9117a969f93ddd2582c964c21acca1f

**Comment by lorenzhs** [comment]
Lots of languages beside Haskell use `foldl` and `foldr`, but `fold_left` and `fold_right` also aren't unheard of (OCaml, Scheme, Scala): https://en.wikipedia.org/wiki/Fold_(higher-order_function)#Folds_in_various_languages. In any case, Timo, you should learn some Haskell even if you don't end up using it!

**Pull request closed without merging**
