### PR TITLE
New container class: d_ary_heap

### PR DESCRIPTION
**Pull request by angriman**
New class implementing an addressable integer d-ary heap.

### CODE REVIEW

**Comment by bingmann** [comment]
I optimized the code a bit: instead of `sift_up()` and `sift_down()` containing swaps there is now a loop which takes out a temporary items and then uses a loop containing moves.
This makes both `push()`/`sift_up()` and `pop()`/`sift_down()` substantially faster:
Speed test before loop change:
[d_ary_heap_speedtest_results1.pdf](https://github.com/tlx/tlx/files/2922800/d_ary_heap_speedtest_results1.pdf)
Speed test after loop change:
[d_ary_heap_speedtest_results2.pdf](https://github.com/tlx/tlx/files/2922802/d_ary_heap_speedtest_results2.pdf)

**Comment by bingmann** [comment]
So, what do you think, @angriman ?

**Comment by angriman** [comment]
I agree with your optimization, caching the item to be sifted up or down and using moves is faster than swapping.

In `sanity_check()` the [mark vector](https://github.com/tlx/tlx/pull/14/files#diff-97dcdfceb4894a4fd0ba6dfd0100f589R206) stores unsigned chars. Why don't you use a bool vector?

**Comment by lorenzhs** [comment]
I would expect that Timo is using unsigned chars because `std::vector<bool>` is not what one would expect. It uses masks etc to access single bits, which is often slower than wasting some space.

**Comment by bingmann** [comment]
Yes, this is debug code used in test, it doesnt matter.

**Pull request merged**
