### PR TITLE
Add RadixHeap

### PR DESCRIPTION
**Pull request by manpen**
As discussed in issue #10

### CODE REVIEW

**Comment by manpen** [comment]
Interesting side note: Uncrustify eats the semicolon in `tlx/radixheap.hpp:591` causing syntax errors ...

**Comment by bingmann** [comment]
Adding more braces or parenthesis usually helps.

**Comment by manpen** [comment]
This is soo LISP of you to say ...
I will move the radixheap into container and fix the MSVC bug

**Comment by manpen** [comment]
Please do not yet merge the PR but feel free to review it.

There are three non-substantial changes I want to make next week:
- Fix MSVC conversion warnings. The conversions themselves are safe in the test case, but better get rid of the warnings.
- Add `std::invoke` (if supported by compiler) to have a more flexible KeyExtract. Sorry that this comes so late, but I only learned about it today.
- Use declval in make_radixheap type deduction

**Comment by manpen** [comment]
Sorry, it took a little longer ;) For me the PR is now in a merge-able state.

**Comment by bingmann** [comment]
Looks good code-wise. but not style-wise:
https://github.com/tlx/tlx/blob/master/CodingStyle.md#naming-of-types-methods-functions-variables
"All types, e.g. classes or typedef/usings are CamelCase"

**Comment by bingmann** [comment]
Hmm. Either it's Radixheap and `radixheap.hpp` or RadixHeap and `radix_heap.hpp`
Sorry.

**Pull request merged**
